-- Supabase project: Moning Associates | East US (North Virginia)
-- https://lktmlevsotbvnkkcrreg.supabase.co
--
-- NOTE: This file documents the LIVE schema shared with the main website
-- (stevenmoning.vercel.app). The admin panel reads/writes `properties` and
-- `blogs` — the same tables the main site renders. Do not create separate
-- admin-only tables (an earlier `listings`/`blog_posts` pair caused the admin
-- and the live site to drift apart).
--
-- RLS: both tables only allow the anon key to SELECT published rows.
-- All admin reads and writes go through the service role
-- (see lib/supabase/server.ts → createAuthedServiceClient).

-- ─── properties ──────────────────────────────────────────────────────────────
-- property_type check: 'luxury' | 'land' | 'off_market'
-- status check:        'draft' | 'published' | 'archived'
-- Notable defaults: state='TX', is_featured=false, pool=false,
--                   garage_spaces=0, stories=1, images='{}', meta='{}'
-- Columns:
--   id uuid PK, title text NOT NULL, slug text, description text,
--   property_type text NOT NULL, status text NOT NULL, is_featured bool,
--   address, city, state, zip_code, neighborhood, county text,
--   price, price_per_sqft, hoa_fee, tax_annual numeric,
--   bedrooms int, bathrooms numeric, half_bathrooms int,
--   square_footage int, lot_size_sqft int, lot_size_acres numeric,
--   year_built int, garage_spaces int, stories int, pool bool,
--   images text[], virtual_tour_url text, video_url text, mls_number text,
--   listing_date date, days_on_market int, meta jsonb,
--   created_at timestamptz, updated_at timestamptz

-- ─── blogs ───────────────────────────────────────────────────────────────────
-- status check: 'draft' | 'published' | 'archived'
-- Default author: 'Steven Moning'
-- Columns:
--   id uuid PK, title text NOT NULL, slug text UNIQUE NOT NULL,
--   excerpt text, content text, cover_image text, author text,
--   tags text[], status text, published_at timestamptz, meta jsonb,
--   created_at timestamptz, updated_at timestamptz

-- ─── Other tables used only by the main website ──────────────────────────────
--   contact_submissions, services, team_members

-- ─── Storage: blog-images bucket (public) ────────────────────────────────────
-- Authenticated users can upload; public can view.
